// src/app/social/page.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub, faYoutube, faXTwitter, faLastfm, faSteam } from '@fortawesome/free-brands-svg-icons'
import { faAt } from '@fortawesome/free-solid-svg-icons'

const socialLinks = [
  { icon: faGithub, name: 'GitHub', username: '@lucmsilva651', url: 'https://github.com/lucmsilva651' },
  { icon: faYoutube, name: 'YouTube', username: 'c/lucmsilva651', url: 'https://youtube.com/c/lucmsilva651' },
  { icon: faXTwitter, name: 'X / Twitter', username: '@lucmsilvagg / @cudemira', url: 'https://twitter.com/lucmsilvagg' },
  { icon: faLastfm, name: 'Last.fm', username: 'lucmsilva', url: 'https://last.fm/user/lucmsilva' },
  { icon: faSteam, name: 'Steam', username: 'lucasgabrielm95 (@lucmsilva)', url: 'https://steamcommunity.com/id/lucmsilva/' },
  { icon: faAt, name: 'Email', username: 'lucmsilva651@gmail.com', url: 'mailto:lucmsilva651@gmail.com' },
]

export default function Social() {
  return (
    <div className="space-y-6">
      <h1 className="text-4xl font-bold">Social media</h1>
      <p>These are my social media profiles:</p>
      <div className="space-y-2">
        {socialLinks.map((link) => (
          <p key={link.name} className="flex items-center">
            <FontAwesomeIcon icon={link.icon} className="mr-2 w-4 h-4" />
            <span className="font-medium">{link.name}:</span>{' '}
            <a
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              className="ml-1 underline hover:text-[#4040ff]"
            >
              {link.username}
            </a>
          </p>
        ))}
      </div>
    </div>
  )
}

// src/pages/Social.vue
<script setup>
import { Icon } from "@iconify/vue";
</script>

<template>
  <section id="social" class="window">
    <div class="title-bar">
      <div class="title-bar-text">Social media</div>
    </div>
    <div class="window-body has-space">
      <p>
        These are some links that you can use to contact me
        <i>(or to just take a look)</i>
      </p>
      <ul class="icon-grid">
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://github.com/lucmsilva651">
            <Icon icon="fa6-brands:github" height="52" />
            <p>GitHub</p>
          </a>
        </li>
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://gitlab.com/lucmsilva">
            <Icon icon="fa-brands:gitlab" height="52" />
            <p>GitLab</p>
          </a>
        </li>
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://t.me/LucasAndroid">
            <Icon icon="fa6-brands:telegram" height="52" />
            <p>Telegram</p>
          </a>
        </li>
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://last.fm/user/lucmsilva">
            <Icon icon="fa6-brands:lastfm-square" height="52" />
            <p>Last.fm</p>
          </a>
        </li>
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://youtube.com/c/lucmsilva651">
            <Icon icon="fa6-brands:youtube" height="52" />
            <p>YouTube</p>
          </a>
        </li>
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://linkedin.com/in/lucmsilva">
            <Icon icon="fa6-brands:linkedin" height="52" />
            <p>LinkedIn</p>
          </a>
        </li>
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://reddit.com/u/lucmsilva">
            <Icon icon="fa6-brands:reddit" height="52" />
            <p>Reddit</p>
          </a>
        </li>
        <li>
          <a target="_blank" rel="noopener noreferrer" href="https://x.com/lucmsilvagg">
            <Icon icon="fa6-brands:twitter" height="52" />
            <p>Twitter / X</p>
          </a>
        </li>
      </ul>
    </div>
  </section>
</template>

<style scoped>
#social {
  max-width: 320px;
}
#social .window-body {
  padding: 20px 30px;
  gap: 30px;
}
</style>
